#!/bin/sh

GIT_WORK_TREE=/root/HW4/deploy/blue-www/ git checkout -f

############## Create docker image  ##################
sudo docker rmi my_image
sudo docker build -t my_image /root/HW4/deploy/blue-www/

############## Pushing to local registry ##################
sudo docker tag -f my_image localhost:5000/docker_image:latest
sudo docker push localhost:5000/docker_image:latest

############## Pull, stop and remove if already existing container ##################
sudo docker pull localhost:5000/docker_image:latest
sudo docker stop $(sudo docker ps -a -f 'name=blue*' -q)
sudo docker rm $(sudo docker ps -a -f 'name=blue*' -q)

sudo docker run -p 8080:8080 -td --name blue1 localhost:5000/docker_image:latest
sudo docker exec -td blue1 sh -c "node /src/main.js 8080"